### ISSUE TITLE
Error 500 on AFAS's end

### ISSUE THREAD

**Issue by BuiltByBucky** [wesimplycode/laravel-afas-rest-connector#1]
Hi, 
I'm experiencing an ERROR 500 (internal server error) on AFAS's end.
Looking into the code is seems like the connector isn't send.

in AfasConnection.php, line 24 there's the getConnector-function where you save the name into a config-array.
The AfasGetConnector expects a string of the connector, not an array.
By removing the array_key_exists check, the config-variable and changing the response to 
return new AfasGetConnector($this, $name."?", $jsonFilter);
this fixed my issue.

If you want I can make a pull request, just let me know.
Not sure anyone else is experiencing the same.

**Comment by sunilvrk** [comment]
Hi @Datalink-Wouter sorry for the late response.

I looked into your issue and i suspect that you haven't set the the connector in the config file. I see i haven't mentioned this in the documentation so my apologies. After publishing the config file you can set different connections and for each connection their own getConnectors & updateConnectors. Make sure to add your getConnector to the getConnectors array of the connection you are using where the key can be anything you want (this will be used in your code as the name for the connector) but the value has to be the id of the connector in AFAS.

The function getConnector() in AfasConnection.php on line 24 expects a name for the connector and a boolean in case you want to use the jsonFilter. It will than look for the AFAS id in the getConnectors array in your config file. If it cant find it it will throw a clear exception.

If this isn't the case for you. Can you send me a specific example where you are using the getConnector and getting the error?
