### ISSUE TITLE
Argument #1 ($content) must be of type ?string

### ISSUE THREAD

**Issue by KalimeroMK** [wesimplycode/laravel-afas-rest-connector#5]
When tray to connect get TypeError: Symfony\Component\HttpFoundation\Response::setContent(): Argument #1 ($content) must be of type ?string, WeSimplyCode\LaravelAfasRestConnector\AfasGetConnector given, called in /var/www/vendor/laravel/framework/src/Illuminate/Http/Response.php on line 72 in file /var/www/vendor/symfony/http-foundation/Response.php on line 396

```
 // Connections to different AFAS servers
    'connections' => [

        'default' => [
            // The environment of the profit service. Ex: T11111AA
            'environment' => env('AFAS_ENVIRONMENT', null),

            // The authorization token to make requests to the profit service
            'token' => env('AFAS_TOKEN', null),

            /*
             * These are placeholders. Replace them with your connectors!
             *
             * You can name the key whatever you want. The value has to be the connector ID in AFAS Profit.
             * You can add as many connectors as needed, just don't forget to add them to your .env file
             */

            // List of all the getConnectors for the profit service
            'getConnectors' => [
                'contacts' => 'MainZusAppconnector'
            ],

            // List of all the updateConnectors for the profit service
            'updateConnectors' => [
                'persons' => ''
            ]
        ]

    ],
``` 
AFAS_ENVIRONMENT 
AFAS_TOKEN
add in .env file

**Comment by sunilvrk** [comment]
Could you please provide an example that triggers this issue?

Also: 
```
// List of all the getConnectors for the profit service
            'getConnectors' => [
                'contacts' => 'MainZusAppconnector' // are you sure this value is correct?
            ],
```
The value is not the name of the appConnector but after you have created an appConnector in AFAS you can than enable getConnectors for the appConnector. The value should be the connector-id.

If you provide me with an example I could help you out further.

**Comment by sunilvrk** [comment]
Here is an example of my config:

```
// List of all the getConnectors for the profit service
'getConnectors' => [
    // Article groups
    'articleGroup' => 'Profit_ArticleGroups',
    // orders
    'orders' => 'Profit_SalesorderLines'
],
```

**Comment by KalimeroMK** [comment]
so my data then is not correct 
i have 
```
URL AFAs connector: https://90071.rest.afas.online/ProfitRestServices/connectors/KraamZusAppMedewerkers
Token: <token><version>1</version><data>EDD1E647F5A8492AA8E7EBC5278D45B3ABA9C32145F672A79....</data></token>
Enviroment:09007... 
```
 what else I need to connect and how pls help

**Comment by sunilvrk** [comment]
Yes i think your config is not correct. Here you can find the docs about get connectors: https://help.afas.nl/help/EN/SE/App_Cnr_Rest_Api.htm#o106273

Here you can find info on how to make an appConnector and add getConnectors to your appConnector. https://help.afas.nl/help/EN/SE/App_Apps_Custom_Add.htm

First create a new app connector. After that double click on the app connector you just created. On the left side of the window that opens you should see a link "GetConnectors". Click on that and you should be able to add getConnectors to your appConnector. The id of the getConnector is what becomes the value in the config file (this id is shown when selecting a getConnector)


https://connect.afas.nl/rest-json/get-connector
That is a tool developed by Afas to test your app connector. You can use this tool to quickly see what getConnectors are enabled for your current appConnector.

I hope this helps and if you have other questions let me know.

If you have posted you token here i would recommend you to remove the appConnector that uses that token en make a new one for security purposes.

**Comment by KalimeroMK** [comment]
ty for the info I will ask the oner to go try this with me so I retrieve all I need the token is not valid  :)

**Comment by sunilvrk** [comment]
No problem. I suggest you follow the steps from the second link i gave, and you should be good to go. Hope it works, let me know if you need help.

**Comment by KalimeroMK** [comment]
I will ty
