### ISSUE TITLE
WeSimplyCode\LaravelAfasRestConnector\AfasConnectionManager::connection(): Argument #2 ($token) must be of type string, null given

### ISSUE THREAD

**Issue by Cube-Justin** [wesimplycode/laravel-afas-rest-connector#8]
Exception: `WeSimplyCode\LaravelAfasRestConnector\AfasConnectionManager::connection(): Argument #2 ($token) must be of type string, null given`

This occurs when using the facade `Afas::getConnector($connector)` without passing a token.
I am guessing that [this PR](https://github.com/wesimplycode/laravel-afas-rest-connector/commit/4c5327ca422b712f50a154e71024be5d2c118106#diff-9cc8d097cde608d5bd2349b7259903268fd732225f3d1913ee4b924b175e58f8) caused this to exist.

**Comment by sunilvrk** [comment]
Hey you are correct in the PR the token and environment were not optional in the AfasConnectionManager. I have made them optional now. Im sorry that bug slipped through. 

Thanks for letting me know.
